### ISSUE TITLE
Issues with concurrent transaction updates and OpenMP analytical algorithms.

### ISSUE THREAD

**Issue by Jiboxiake** [cwida/teseo#1]
I am using a newer version of gfe https://github.com/PerFuchs/gfe_driver and TESEO seems to have deadlocks when running both updates and analytical workloads concurrently. Basically it runs the same aging experiment for the first 10% of the workload and then starts a graphalytics instance on the dynamic graph. In both BFS and PageRank, TESEO is able to finish some runs of the concurrent analytics but later around 30% to 50% of the workload the whole system becomes unresponsive. Either writers or readers can proceed forward. I'm wondering if it is due to an internal bug or due to some configuration issue. Thanks so much in advance.

**Comment by whatsthecraic** [comment]
This is a known deadlock unfortunately, Per also reported it and it's the issue that he mentions in his paper. At the time, I was never able to reproduce it in my machine. It's puzzling it only happens when there are concurrent readers, because with only writers it doesn't seem to surface. It must be a reader causing a bad state when leaving the critical section, I'm afraid I wasn't able to find out where this actually originates.

**Comment by Jiboxiake** [comment]
Hello, thank you and I went back to the paper and found out that yes he did mention it. Sorry it was the carelessness on my end. I agree in my experiments the pure writers scenarios are all successful. I will then proceed with those in mind. Thanks.
